// Auto-generated by src/components/libs/Icon/collections/generate.js
// Do not edit manually!

// Import maps from individual files
import { mdiIcons } from './mdi-icons';
import { faSolidIcons } from './fa-solid-icons';
import { tablerIcons } from './tabler-icons';
import { featherIcons } from './feather-icons';
import { phIcons } from './ph-icons';
import { heroiconsSolidIcons } from './heroicons-solid-icons';
import { lineMdIcons } from './line-md-icons';


// Interface for a single icon set
export interface IconSet {
  label: string;
  key: string;
  icons: { [PascalCaseName: string]: string }; // Map PascalCase name to 'prefix:kebab-name'
}

// Array containing all processed icon sets
export const iconSets: IconSet[] = [
  {
    label: 'Material',
    key: 'mdi',
    icons: mdiIcons // Use imported variable
  },
  {
    label: 'Font Awesome Solid',
    key: 'fa-solid',
    icons: faSolidIcons // Use imported variable
  },
  {
    label: 'Tabler Icons',
    key: 'tabler',
    icons: tablerIcons // Use imported variable
  },
  {
    label: 'Feather Icons',
    key: 'feather',
    icons: featherIcons // Use imported variable
  },
  {
    label: 'Phosphor Icons',
    key: 'ph',
    icons: phIcons // Use imported variable
  },
  {
    label: 'Heroicons Solid',
    key: 'heroicons-solid',
    icons: heroiconsSolidIcons // Use imported variable
  },
  {
    label: 'Line Material Design',
    key: 'line-md',
    icons: lineMdIcons // Use imported variable
  }
];

// Optional: Flattened map for direct lookup by PascalCase name across all sets.
// Note: If icons share the same PascalCase name across sets, the last one processed wins.
export const allIcons: { [PascalCaseName: string]: string } = (() => {
  const acc = {};
    Object.assign(acc, mdiIcons);
    Object.assign(acc, faSolidIcons);
    Object.assign(acc, tablerIcons);
    Object.assign(acc, featherIcons);
    Object.assign(acc, phIcons);
    Object.assign(acc, heroiconsSolidIcons);
    Object.assign(acc, lineMdIcons);
  return acc;
})();

// Paths to the original JSON icon data files (relative to project root)
export const iconJsonPaths: { [key: string]: string } = {
  'mdi': '/static/icons/mdi.json',
  'fa-solid': '/static/icons/fa-solid.json',
  'tabler': '/static/icons/tabler.json',
  'feather': '/static/icons/feather.json',
  'ph': '/static/icons/ph.json',
  'heroicons-solid': '/static/icons/heroicons-solid.json',
  'line-md': '/static/icons/line-md.json'
};

